version: "3.8"

services: 
    imap:
        container_name: imap
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        build: 
            context: ../../../
            dockerfile: provision/environments/development/Dockerfile-imap
            shm_size: 12G
        user: 1000:1000
        tty: true
        volumes:
            - ../../../applications/implicit_mapping:/home/scratch/implicit_mapping
        ports: 
            - 3000:3000