name: CI

on: [pull_request]

env:
  DOCKER_COMPOSE_DIRECTORY: provision/environments/continuous-integration
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - run: pwd && docker-compose --version && docker --version

    - run: docker-compose build --parallel
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}
    - run: docker-compose up -d
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

    - run: docker-compose exec -T imap make black
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}
    - run: docker-compose exec -T imap make flake8
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}    
    - run: docker-compose exec -T imap make isort
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}
    - run: docker-compose exec -T imap make mypy
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}


      # pytest-cov export coverage data to a file
      # However, the directory made by actions/checkout does not allow write
      # chmod is needed to resolve above problem
    - run: chmod 777 .
      working-directory: applications/implicit_mapping
    - run: docker-compose exec -T imap make test
      working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}